### ISSUE TITLE
make desktop fails with stale node_modules: cannot find @tanstack/react-query

### ISSUE THREAD

**Issue by kmtusher97** [kamrul1157024/helios#123]
## Description

Running `make desktop-install` (or any target that depends on `desktop`) fails during typecheck with a wall of errors, even though the dependency is declared in `desktop/package.json` and present in `desktop/package-lock.json`:

```
src/renderer/host-data.ts(1,28): error TS2307: Cannot find module '@tanstack/react-query' or its corresponding type declarations.
... (plus cascading TS7006/TS7031 implicit-any errors)
make: *** [desktop] Error 2
```

## Root cause

The `desktop` make target only installs deps when `node_modules` is **absent**:

```makefile
@if [ ! -d desktop/node_modules ]; then cd desktop && npm install; fi
```

A `node_modules` tree left over from before a dependency was added (e.g. `@tanstack/react-query`, introduced in #114) satisfies the existence check, so `npm install` is skipped and the stale tree is used — producing the confusing "cannot find module" typecheck errors.

## Steps to reproduce

1. Have a `desktop/node_modules` that predates a newly added dependency.
2. Run `make desktop` (or `make desktop-install`).
3. Typecheck fails with `TS2307: Cannot find module '@tanstack/react-query'`.

## Expected

The build should detect the stale tree and reinstall deps before building.

## Workaround

`cd desktop && npm install` (or `npm ci`) manually before building.
